apiVersion: scheduler.kalypso.io/v1alpha1
kind: BaseRepo
metadata:
  name: main
spec:
  repo: https://github.com/eedorenko/kalypso-tut-test-control-plane
  branch: main
  path: .
  commit: 281a9cbe37c87c4fa8f31cc1b1795028b3845bb2
